version: "3.7"

services:
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command: ["start", "--all"]
    ports:
      - "4040:4040"
    volumes:
      - ${APP_DATA_DIR}/config/ngrok:/home/umbrel/.config/ngrok

